
>>> cv2.imread('crop1.tif',-1)
array([[42785, 42855, 42877, ..., 42419, 42273, 42321],
       [42661, 42957, 42922, ..., 42285, 42220, 42322],
       [42537, 43060, 42967, ..., 42151, 42167, 42323],
       ...,
       [42340, 42423, 42512, ..., 42156, 42043, 42233],
       [42295, 42415, 42589, ..., 42075, 41869, 42157],
       [42203, 42530, 42602, ..., 42140, 41821, 42022]], dtype=uint16)
>>> test = cv2.imread('crop1.tif',-1)
>>> cv2.imshow('',test)              
>>> OD
array([[1.98811821e-05, 1.98811821e-05, 1.98811821e-05, ...,
        6.05258746e-03, 6.13323389e-03, 4.54992974e-03],
       [1.98811821e-05, 1.98811821e-05, 1.98811821e-05, ...,
        5.71000709e-03, 4.95862076e-03, 4.71068032e-03],
       [1.98811821e-05, 1.98811821e-05, 1.98811821e-05, ...,
        5.36769675e-03, 3.78717598e-03, 4.87149042e-03],
       ...,
       [1.98811821e-05, 1.98811821e-05, 7.29021176e-05, ...,
        3.51986025e-03, 4.89829789e-03, 4.65709018e-03],
       [1.98811821e-05, 1.98811821e-05, 4.63908407e-05, ...,
        2.36561069e-03, 5.41466455e-03, 4.36246256e-03],
       [1.98811821e-05, 1.98811821e-05, 1.98811821e-05, ...,
        1.21442071e-03, 5.93164588e-03, 4.06803469e-03]])
>>> d.OD
<bound method Calibrate.OD of <EBT3.Calibrate object at 0x7fb6eb540cd0>>
>>> OD = np.log10(65535.0/test[:,:,2]) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
>>> OD = np.log10(65535.0/test[:,:,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
>>> tets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tets' is not defined
>>> test
array([[42785, 42855, 42877, ..., 42419, 42273, 42321],
       [42661, 42957, 42922, ..., 42285, 42220, 42322],
       [42537, 43060, 42967, ..., 42151, 42167, 42323],
       ...,
       [42340, 42423, 42512, ..., 42156, 42043, 42233],
       [42295, 42415, 42589, ..., 42075, 41869, 42157],
       [42203, 42530, 42602, ..., 42140, 41821, 42022]], dtype=uint16)
>>> test[:,:,2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
>>> test[:,:]  
array([[42785, 42855, 42877, ..., 42419, 42273, 42321],
       [42661, 42957, 42922, ..., 42285, 42220, 42322],
       [42537, 43060, 42967, ..., 42151, 42167, 42323],
       ...,
       [42340, 42423, 42512, ..., 42156, 42043, 42233],
       [42295, 42415, 42589, ..., 42075, 41869, 42157],
       [42203, 42530, 42602, ..., 42140, 41821, 42022]], dtype=uint16)
>>> OD = np.log10(65535.0/test)       
>>> OD
array([[0.18518177, 0.1844718 , 0.18424891, ..., 0.18891288, 0.19041023,
        0.18991738],
       [0.18644227, 0.18343936, 0.18379335, ..., 0.19028697, 0.19095507,
        0.18990712],
       [0.18770645, 0.18239928, 0.18333827, ..., 0.19166542, 0.1915006 ,
        0.18989686],
       ...,
       [0.18972245, 0.18887193, 0.18796177, ..., 0.19161391, 0.19277961,
        0.19082137],
       [0.19018427, 0.18895383, 0.18717586, ..., 0.19244918, 0.19458072,
        0.19160361],
       [0.19112998, 0.18777792, 0.18704332, ..., 0.19177877, 0.19507889,
        0.19299659]])
>>> Dose = f.coeff[0]*(OD**2)+f.coeff[1]*(OD)+f.coeff[2]
>>> Dose
array([[0.27544518, 0.27699189, 0.2774861 , ..., 0.26800452, 0.26534345,
        0.26619879],
       [0.27280218, 0.27931582, 0.27850905, ..., 0.26555549, 0.26442136,
        0.26621681],
       [0.27028397, 0.28174643, 0.27954812, ..., 0.26325618, 0.26352281,
        0.26623484],
       ...,
       [0.26654265, 0.26807991, 0.26979149, ..., 0.26333927, 0.26151298,
        0.26464536],
       [0.2657331 , 0.26792926, 0.27132473, ..., 0.2620192 , 0.258913  ,
        0.26335592],
       [0.26413058, 0.27014556, 0.27158837, ..., 0.26307413, 0.25824142,
        0.26118549]])
>>> np.max(Dose)
2.0117454697426944
>>> np.min(Dose)
0.24762979054169598
>>> cv2.imshow(Dose)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)

>>> cv2.imshow('',Dose)
>>> fig = plt.subplots()
>>> plt.imshow(Dose)
<matplotlib.image.AxesImage object at 0x7fb6d2683b50>
>>> plt.colorbar()
<matplotlib.colorbar.Colorbar object at 0x7fb6d237e640>
>>> plt.show()
kf.kio.widgets.kdirmodel: No node found for item that was just removed: QUrl("file:///home/filippo/2021-02-19 15-17-11.mkv")
>>> 
